install:
    script: |
        echo Entering install phase

        sudo npm install -g pm2
        pm2 kill

        sudo kill -9 `sudo lsof -t -i:5000`
        sudo kill -9 `sudo lsof -t -i:5001`
        sudo kill -9 `sudo lsof -t -i:5002`
        sudo kill -9 `sudo lsof -t -i:5003`
        sudo kill -9 `sudo lsof -t -i:5006`
        sudo kill -9 `sudo lsof -t -i:5007`
        
        sudo rm -rf /spaceduck/*
        aws s3 cp s3://{bucketName}/{filePath}.zip /spaceduck/code.zip
        unzip /spaceduck/code.zip -d /spaceduck/code

        sudo mkdir -p /spaceduck/logs

        echo Install phase complete

build:
    script: |
        echo Entering build phase

        echo Building UserService
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.UserService
        # sudo dotnet publish -o /spaceduck/out/bin/SpaceDuck.UserService -v n
        sudo dotnet build
        echo Build complete

        echo Building Chess
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.ChessGame
        # sudo dotnet publish -o /spaceduck/out/bin/SpaceDuck.ChessGame -v n
        sudo dotnet build
        echo Build complete

        echo Building Kalambury
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.KalamburyGame
        # sudo dotnet publish -o /spaceduck/out/bin/SpaceDuck.KalamburyGame -v n
        sudo dotnet build
        echo Build complete

        echo Installing UserService frontend
        sudo npm install --prefix /spaceduck/out /spaceduck/code/SpaceDuckFrontend/spaceduck/ --loglevel verbose
        echo UserService frontend installed
        echo Installing Chess frontend
        sudo npm install --prefix /spaceduck/out /spaceduck/code/SpaceDuckFrontend/szachy/ --loglevel verbose
        echo Chess frontend installed
        echo Installing Kalambury frontend
        sudo npm install --prefix /spaceduck/out /spaceduck/code/SpaceDuckFrontend/kalambury/ --loglevel verbose
        sudo npm install --global cross-env
        echo Kalambury frontend installed
        echo Build phase complete

test:
    script: |
        echo Entering test phase
        echo Test phase complete

deploy:
    script: |
        echo Entering deploy phase
        

        echo Starting UserService backend
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.UserService
        sudo sh -c 'nohup dotnet run > /spaceduck/logs/userservice.log 2>&1 &'
        echo UserService started

        echo Starting Chess backend
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.ChessGame
        sudo sh -c 'nohup dotnet run > /spaceduck/logs/chess.log 2>&1 &'
        echo Chess started

        echo Starting Kalambury backend
        cd /spaceduck/code/SpaceDuck.UserService/SpaceDuck.KalamburyGame
        sudo sh -c 'nohup dotnet run > /spaceduck/logs/kalambury.log 2>&1 &'
        echo Kalambury started

        echo Starting UserService frontend
        pm2 start npm --name "spaceduck" -- start --prefix /spaceduck/out/node_modules/spaceduck
        echo UserService started
        
        echo Starting Chess frontend
        pm2 start npm --name "chess" -- start --prefix /spaceduck/out/node_modules/szachy
        echo Chess started

        echo Starting Kalambury frontend
        pm2 start npm --name "kalambury" -- start --prefix /spaceduck/out/node_modules/kalambury
        echo Kalambury started

        echo Deploy phase complete